Fix bugs

diff --git a/dotfiles_apply b/dotfiles_apply
--- a/dotfiles_apply
+++ b/dotfiles_apply
@@ -37,55 +37,65 @@ if (( $? != 0 ));then
     exit $?
 fi
 
-TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
-TARGET="${TARGET/#\~/$HOME}" 
-echo "[+] Targeting '$TARGET'"
+read -r dep_count <  "$MODULE/.dep_count"
+((dep_count++))
+if [[ ! -e "$MODULE/.is_not_dep" ]];then
 
-if [[ ! -d "$TARGET" ]]; then
-    echo "[!] Fatal: The target directory '$TARGET' does not exist or is not a directory"
-    exit 6
-fi
-
-stow --target "$TARGET"    \
-     --dir "$DOTFILES_DIR" \
-     --ignore="$MODULE/.target"    \
-     --ignore="$MODULE/.stow-local-ignore" \
-     --ignore="$MODULE/.dependencies" \
-     --ignore="$MODULE/.is_not_dep" \
-     --ignore="$MODULE/.dep_count" \
-     --ignore="$MODULE/.gitignore" \
-     --verbose             \
-     $1 2>&1
-
-if (( $? != 0 ));then
-    echo "[!] Fatal: An error happened with stow"
-    exit 7
-fi
-
-
-if [[ $IS_DEP -eq 1 ]];then
-    read -r dep_count <  "$MODULE/.dep_count"
-    ((dep_count++))
-    echo "$dep_count" > "$MODULE/.dep_count"
+    mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
+    if (( ${#DEPENDENCIES[@]} > 0 ));then 
+        echo "[+] Adding dependencies to list"
+        printf '  - %s\n' "${DEPENDENCIES[@]}"
+        echo "[#] Applying dependencies first"
+        FLAGGED=()
+        for dep in "${DEPENDENCIES[@]}"; do
+            FLAGGED+=("-d" "$dep")
+        done
+        "$0" "${FLAGGED[@]}"
+        echo "[+] Dependencies applied"
+        echo "[#] Applying main module '$1' now"
+    fi
+    
+    TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
+    TARGET="${TARGET/#\~/$HOME}" 
+    echo "[+] Targeting '$TARGET'"
+    
+    if [[ ! -d "$TARGET" ]]; then
+        echo "[!] Fatal: The target directory '$TARGET' does not exist or is not a directory"
+        exit 6
+    fi
+    
+    
+    stow --target "$TARGET"                 \
+         --dir "$DOTFILES_DIR"              \
+         --ignore="^\.target$"              \
+         --ignore="^\.stow-local-ignore$"   \
+         --ignore="^\.dependencies$"        \
+         --ignore="^\.is_not_dep$"          \
+         --ignore="^\.dep_count$"           \
+         --ignore="^\.gitignore$"           \
+         --verbose                          \
+         $1 2>&1
+    
+    if (( $? != 0 ));then
+        echo "[!] Fatal: An error happened with stow"
+        exit 7
+    fi
+    
+    echo "[=] All '$1' symlinks successfully created"
+    
+    if (( $IS_DEP == 0 ));then
+        touch "$MODULE/.is_not_dep"
+    fi
+    echo "$dep_count" > "$MODULE/.dep_count"  #if it hasn't been applied add count 
 else 
-    echo "1" > "$MODULE/.dep_count"
-    touch "$MODULE/.is_not_dep"
-fi
-
-echo "[=] All '$1' symlinks successfully created"
-
-mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
-if (( ${#DEPENDENCIES[@]} > 0 ));then 
-    echo "[+] Adding dependencies to list"
-    printf '  - %s\n' "${DEPENDENCIES[@]}"
+    if (( $IS_DEP == 1 ));then #if it has already been applied, but it's a dependency, add count
+        echo "$dep_count" > "$MODULE/.dep_count"
+    fi
+    echo "[=] Module has already been applied, skipping"
 fi
 
 shift 
-if (( $# > 0 || ${#DEPENDENCIES[@]} > 0 ));then
-    FLAGGED=()
-    for dep in "${DEPENDENCIES[@]}"; do
-        FLAGGED+=("-d" "$dep")
-    done
+if (( $# > 0 ));then
     echo "[#] Proceeding with next item"
-    exec "$0" $@ "${FLAGGED[@]}"
+    exec "$0" "$@"
 fi
diff --git a/dotfiles_remove b/dotfiles_remove
--- a/dotfiles_remove
+++ b/dotfiles_remove
@@ -8,8 +8,8 @@ fi
 
 if [[ -z "$DOTFILES_DIR" ]]; then
     echo "[!] Fatal: DOTFILES_DIR is not set" >&2
-    echo "    this usually happens when someone tries to execute 'dotfiles_apply' directly" >&2
-    echo "    which is not recommended. Instead use 'dotfiles apply' which is a wrapper that" >&2
+    echo "    this usually happens when someone tries to execute '$0' directly" >&2
+    echo "    which is not recommended. Instead use '${0//_/ }' which is a wrapper that" >&2
     echo "    sets all required environment variables." >&2
     exit 2
 fi
@@ -27,45 +27,48 @@ if (( $? != 0 ));then
     exit $?
 fi
 
-TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
-TARGET="${TARGET/#\~/$HOME}" 
-echo "[+] Targeting '$TARGET'"
-
-if [[ ! -d "$TARGET" ]]; then
-    echo "[!] Fatal: The target directory '$TARGET' does not exist"
-    exit 6
-fi
+DEPENDENCIES=()
 
 dep_count=0
 read -r dep_count <  "$MODULE/.dep_count"
 ((dep_count--))
-if (( $dep_count < 0 ));then 
-    dep_count=0
-fi
-echo "$dep_count" > "$MODULE/.dep_count"
-
-DEPENDENCIES=()
-if (( $dep_count == 0 ));then
-    stow --target "$TARGET"    \
-         --dir "$DOTFILES_DIR" \
-         --verbose             \
-         --delete              \
-         $1 2>&1
-
-    if [[ $? != 0 ]];then
-        echo "[!] Fatal: An error happened with stow"
-        exit 7
+if (( $dep_count >= 0 ));then 
+    TARGET="$("$DOTFILES_DIR/process" "$MODULE/.target")"
+    TARGET="${TARGET/#\~/$HOME}" 
+    echo "[+] Targeting '$TARGET'"
+    
+    if [[ ! -d "$TARGET" ]]; then
+        echo "[!] Fatal: The target directory '$TARGET' does not exist"
+        exit 6
     fi
     
-    echo "[=] All '$1' symlinks successfully removed"
     
-    if [[ -e "$MODULE/.is_not_dep" ]];then
-        rm "$MODULE/.is_not_dep"
+    echo "$dep_count" > "$MODULE/.dep_count"
+    
+    if (( $dep_count == 0 ));then
+        stow --target "$TARGET"    \
+             --dir "$DOTFILES_DIR" \
+             --verbose             \
+             --delete              \
+             $1 2>&1
+    
+        if [[ $? != 0 ]];then
+            echo "[!] Fatal: An error happened with stow"
+            exit 7
+        fi
+        
+        echo "[=] All '$1' symlinks successfully removed"
+        
+        if [[ -e "$MODULE/.is_not_dep" ]];then
+            rm "$MODULE/.is_not_dep"
+        fi
+        
+        mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
+    else
+        echo "[+] Skipped because it's still a dependency"
     fi
-    
-    mapfile -t DEPENDENCIES < <("$DOTFILES_DIR/process" "$MODULE/.dependencies")
-else
-    echo "[+] Skipped because it's still a dependency"
+else 
+    echo "[=] Skipped because it has already been completely removed"
 fi
 
 shift 
